import type { ProviderDef } from './types'

export const PROVIDERS: ProviderDef[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    requiresApiKey: true,
    apiKeyLabel: 'OpenAI API Key',
    apiKeyHelpUrl: 'https://platform.openai.com/api-keys',
    models: [
      { id: 'gpt-4.1', name: 'GPT-4.1' },
      { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini' },
      { id: 'gpt-4o', name: 'GPT-4o' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini' },
      { id: 'o4-mini', name: 'O4 Mini' },
      { id: 'gpt-5', name: 'GPT-5' },
      { id: 'gpt-5-mini', name: 'GPT-5 Mini' },
      { id: 'o3', name: 'O3' },
      { id: 'o3-mini', name: 'O3 Mini' },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    requiresApiKey: true,
    apiKeyLabel: 'Anthropic API Key',
    apiKeyHelpUrl: 'https://console.anthropic.com/settings/keys',
    models: [
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6' },
      { id: 'claude-opus-4-8', name: 'Claude Opus 4.8' },
      { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5' },
      { id: 'claude-sonnet-4-5', name: 'Claude Sonnet 4.5' },
      { id: 'claude-opus-4-5', name: 'Claude Opus 4.5' },
      { id: 'claude-fable-5', name: 'Claude Fable 5' },
    ],
  },
  {
    id: 'google',
    name: 'Google AI',
    requiresApiKey: true,
    apiKeyLabel: 'Google AI API Key',
    apiKeyHelpUrl: 'https://aistudio.google.com/apikey',
    models: [
      { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro' },
      { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash' },
      { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash' },
      { id: 'gemini-2.0-flash-lite', name: 'Gemini 2.0 Flash Lite' },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    requiresApiKey: true,
    apiKeyLabel: 'Groq API Key',
    apiKeyHelpUrl: 'https://console.groq.com/keys',
    models: [
      { id: 'llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout' },
      { id: 'llama-4-maverick-17b-128e-instruct', name: 'Llama 4 Maverick' },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 70B' },
      { id: 'qwen-2.5-32b', name: 'Qwen 2.5 32B' },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    requiresApiKey: true,
    apiKeyLabel: 'Mistral API Key',
    apiKeyHelpUrl: 'https://console.mistral.ai/api-keys',
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large' },
      { id: 'mistral-small-latest', name: 'Mistral Small' },
      { id: 'codestral-latest', name: 'Codestral' },
      { id: 'mistral-nemo-latest', name: 'Mistral Nemo' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    requiresApiKey: true,
    apiKeyLabel: 'DeepSeek API Key',
    apiKeyHelpUrl: 'https://platform.deepseek.com/api_keys',
    models: [
      { id: 'deepseek-chat', name: 'DeepSeek V3' },
      { id: 'deepseek-reasoner', name: 'DeepSeek R1' },
    ],
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    requiresApiKey: true,
    apiKeyLabel: 'xAI API Key',
    apiKeyHelpUrl: 'https://console.x.ai',
    models: [
      { id: 'grok-4', name: 'Grok 4' },
      { id: 'grok-4-mini', name: 'Grok 4 Mini' },
      { id: 'grok-3', name: 'Grok 3' },
      { id: 'grok-3-mini', name: 'Grok 3 Mini' },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    requiresApiKey: true,
    apiKeyLabel: 'Perplexity API Key',
    apiKeyHelpUrl: 'https://www.perplexity.ai/settings/api',
    models: [
      { id: 'sonar-pro', name: 'Sonar Pro' },
      { id: 'sonar', name: 'Sonar' },
      { id: 'sonar-reasoning-pro', name: 'Sonar Reasoning Pro' },
      { id: 'sonar-reasoning', name: 'Sonar Reasoning' },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    requiresApiKey: true,
    apiKeyLabel: 'Cohere API Key',
    apiKeyHelpUrl: 'https://dashboard.cohere.com/api-keys',
    models: [
      { id: 'command-r-plus', name: 'Command R+' },
      { id: 'command-r', name: 'Command R' },
      { id: 'command-a', name: 'Command A' },
    ],
  },
  {
    id: 'togetherai',
    name: 'Together AI',
    requiresApiKey: true,
    apiKeyLabel: 'Together API Key',
    apiKeyHelpUrl: 'https://api.together.ai/settings/api-keys',
    models: [
      { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', name: 'Llama 4 Maverick' },
      { id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', name: 'Llama 4 Scout' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3' },
      { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', name: 'Qwen 2.5 72B' },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    requiresApiKey: true,
    apiKeyLabel: 'Fireworks API Key',
    apiKeyHelpUrl: 'https://fireworks.ai/account/api-keys',
    models: [
      { id: 'accounts/fireworks/models/llama4-maverick-instruct-basic', name: 'Llama 4 Maverick' },
      { id: 'accounts/fireworks/models/deepseek-r1', name: 'DeepSeek R1' },
      { id: 'accounts/fireworks/models/deepseek-v3', name: 'DeepSeek V3' },
      { id: 'accounts/fireworks/models/qwen2p5-72b-instruct', name: 'Qwen 2.5 72B' },
    ],
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    requiresApiKey: true,
    apiKeyLabel: 'Cerebras API Key',
    apiKeyHelpUrl: 'https://cloud.cerebras.ai/api-keys',
    models: [
      { id: 'llama-4-maverick-17b-128e-instruct-fp8', name: 'Llama 4 Maverick' },
      { id: 'llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout' },
      { id: 'llama3.3-70b', name: 'Llama 3.3 70B' },
    ],
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    requiresApiKey: true,
    apiKeyLabel: 'AWS Access Key ID',
    apiKeyHelpUrl: 'https://console.aws.amazon.com/iam',
    models: [
      { id: 'us.anthropic.claude-sonnet-4-6-v1:0', name: 'Claude Sonnet 4.6' },
      { id: 'us.anthropic.claude-opus-4-8-v1:0', name: 'Claude Opus 4.8' },
      { id: 'us.anthropic.claude-haiku-4-5-v1:0', name: 'Claude Haiku 4.5' },
      { id: 'us.meta.llama4-maverick-17b-instruct-v1:0', name: 'Llama 4 Maverick' },
    ],
    extraFields: [
      { name: 'secretKey', label: 'AWS Secret Access Key', type: 'text', placeholder: 'Your AWS secret key' },
      { name: 'region', label: 'AWS Region', type: 'text', placeholder: 'us-east-1' },
    ],
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    requiresApiKey: true,
    apiKeyLabel: 'Azure API Key',
    apiKeyHelpUrl: 'https://portal.azure.com',
    models: [
      { id: 'gpt-4.1', name: 'GPT-4.1' },
      { id: 'gpt-4o', name: 'GPT-4o' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini' },
    ],
    extraFields: [
      { name: 'resourceName', label: 'Resource Name', type: 'text', placeholder: 'my-resource' },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    requiresApiKey: true,
    apiKeyLabel: 'OpenRouter API Key',
    apiKeyHelpUrl: 'https://openrouter.ai/keys',
    isOpenAICompatible: true,
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    models: [
      { id: 'anthropic/claude-sonnet-4-6', name: 'Claude Sonnet 4.6' },
      { id: 'anthropic/claude-opus-4-8', name: 'Claude Opus 4.8' },
      { id: 'openai/gpt-5', name: 'GPT-5' },
      { id: 'openai/gpt-4.1', name: 'GPT-4.1' },
      { id: 'google/gemini-2.5-pro', name: 'Gemini 2.5 Pro' },
      { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1' },
      { id: 'meta-llama/llama-4-maverick', name: 'Llama 4 Maverick' },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    requiresApiKey: false,
    apiKeyLabel: 'No API Key Required',
    apiKeyHelpUrl: 'https://ollama.com',
    isOpenAICompatible: true,
    defaultBaseUrl: 'http://localhost:11434/v1',
    models: [
      { id: 'llama3.3', name: 'Llama 3.3' },
      { id: 'llama3.2', name: 'Llama 3.2' },
      { id: 'qwen2.5', name: 'Qwen 2.5' },
      { id: 'codellama', name: 'Code Llama' },
      { id: 'mistral', name: 'Mistral' },
      { id: 'deepseek-r1', name: 'DeepSeek R1' },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    requiresApiKey: false,
    apiKeyLabel: 'No API Key Required',
    apiKeyHelpUrl: 'https://lmstudio.ai',
    isOpenAICompatible: true,
    defaultBaseUrl: 'http://localhost:1234/v1',
    models: [{ id: 'auto', name: 'Auto (use loaded model)' }],
  },
  {
    id: 'custom',
    name: 'Custom OpenAI-Compatible',
    requiresApiKey: false,
    apiKeyLabel: 'API Key (optional)',
    apiKeyHelpUrl: '',
    isOpenAICompatible: true,
    defaultBaseUrl: '',
    models: [{ id: 'custom', name: 'Custom Model' }],
    extraFields: [
      { name: 'baseUrl', label: 'Base URL', type: 'url', placeholder: 'https://api.example.com/v1', helpText: 'OpenAI-compatible API endpoint' },
    ],
  },
]

export function getProvider(id: string): ProviderDef | undefined {
  return PROVIDERS.find((p) => p.id === id)
}
