import type { ProviderDef } from './types'

export const PROVIDERS: ProviderDef[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    requiresApiKey: true,
    apiKeyLabel: 'OpenAI API Key',
    apiKeyHelpUrl: 'https://platform.openai.com/api-keys',
    models: [],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    requiresApiKey: true,
    apiKeyLabel: 'Anthropic API Key',
    apiKeyHelpUrl: 'https://console.anthropic.com/settings/keys',
    models: [],
  },
  {
    id: 'google',
    name: 'Google AI',
    requiresApiKey: true,
    apiKeyLabel: 'Google AI API Key',
    apiKeyHelpUrl: 'https://aistudio.google.com/apikey',
    models: [],
  },
  {
    id: 'groq',
    name: 'Groq',
    requiresApiKey: true,
    apiKeyLabel: 'Groq API Key',
    apiKeyHelpUrl: 'https://console.groq.com/keys',
    models: [],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    requiresApiKey: true,
    apiKeyLabel: 'Mistral API Key',
    apiKeyHelpUrl: 'https://console.mistral.ai/api-keys',
    models: [],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    requiresApiKey: true,
    apiKeyLabel: 'DeepSeek API Key',
    apiKeyHelpUrl: 'https://platform.deepseek.com/api_keys',
    models: [],
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    requiresApiKey: true,
    apiKeyLabel: 'xAI API Key',
    apiKeyHelpUrl: 'https://console.x.ai',
    models: [],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    requiresApiKey: true,
    apiKeyLabel: 'Perplexity API Key',
    apiKeyHelpUrl: 'https://www.perplexity.ai/settings/api',
    models: [],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    requiresApiKey: true,
    apiKeyLabel: 'Cohere API Key',
    apiKeyHelpUrl: 'https://dashboard.cohere.com/api-keys',
    models: [],
  },
  {
    id: 'togetherai',
    name: 'Together AI',
    requiresApiKey: true,
    apiKeyLabel: 'Together API Key',
    apiKeyHelpUrl: 'https://api.together.ai/settings/api-keys',
    models: [],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    requiresApiKey: true,
    apiKeyLabel: 'Fireworks API Key',
    apiKeyHelpUrl: 'https://fireworks.ai/account/api-keys',
    models: [],
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    requiresApiKey: true,
    apiKeyLabel: 'Cerebras API Key',
    apiKeyHelpUrl: 'https://cloud.cerebras.ai/api-keys',
    models: [],
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    requiresApiKey: true,
    apiKeyLabel: 'AWS Access Key ID',
    apiKeyHelpUrl: 'https://console.aws.amazon.com/iam',
    models: [],
    extraFields: [
      { name: 'secretKey', label: 'AWS Secret Access Key', type: 'text', placeholder: 'Your AWS secret key' },
      { name: 'region', label: 'AWS Region', type: 'text', placeholder: 'us-east-1' },
    ],
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    requiresApiKey: true,
    apiKeyLabel: 'Azure API Key',
    apiKeyHelpUrl: 'https://portal.azure.com',
    models: [],
    extraFields: [
      { name: 'resourceName', label: 'Resource Name', type: 'text', placeholder: 'my-resource' },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    requiresApiKey: true,
    apiKeyLabel: 'OpenRouter API Key',
    apiKeyHelpUrl: 'https://openrouter.ai/keys',
    isOpenAICompatible: true,
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    models: [],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    requiresApiKey: false,
    apiKeyLabel: 'No API Key Required',
    apiKeyHelpUrl: 'https://ollama.com',
    isOpenAICompatible: true,
    defaultBaseUrl: 'http://localhost:11434/v1',
    models: [],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    requiresApiKey: false,
    apiKeyLabel: 'No API Key Required',
    apiKeyHelpUrl: 'https://lmstudio.ai',
    isOpenAICompatible: true,
    defaultBaseUrl: 'http://localhost:1234/v1',
    models: [],
  },
  {
    id: 'custom',
    name: 'Custom OpenAI-Compatible',
    requiresApiKey: false,
    apiKeyLabel: 'API Key (optional)',
    apiKeyHelpUrl: '',
    isOpenAICompatible: true,
    defaultBaseUrl: '',
    models: [],
    extraFields: [
      { name: 'baseUrl', label: 'Base URL', type: 'url', placeholder: 'https://api.example.com/v1', helpText: 'OpenAI-compatible API endpoint' },
    ],
  },
]

export function getProvider(id: string): ProviderDef | undefined {
  return PROVIDERS.find((p) => p.id === id)
}
